<?
$mail_html = '';
$mail_html = $mail_html .= '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">';
$mail_html = $mail_html .= '<html xmlns="http://www.w3.org/1999/xhtml">';
$mail_html = $mail_html .= '<head>';
$mail_html = $mail_html .= '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />';
$mail_html = $mail_html .= '<title>리워디 비밀번호 재설정</title>';
$mail_html = $mail_html .= '<meta name="viewport" content="width=device-width, initial-scale=1.0"/>';
$mail_html = $mail_html .= '</head>';
$mail_html = $mail_html .= '<body style="margin:0;padding:0;">';
$mail_html = $mail_html .= '	<table border="0" cellpadding="0" cellspacing="0" width="100%" id="bodyTable" style="margin:0 auto;text-align:center;">';
$mail_html = $mail_html .= '		<tr>';
$mail_html = $mail_html .= '			<td style="padding-bottom:30px;">';
$mail_html = $mail_html .= '				<table bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" width="100%" style="margin:0 auto;text-align:center;min-width:360px;max-width:740px;">';
$mail_html = $mail_html .= '					<tr>';
$mail_html = $mail_html .= '						<td>';
$mail_html = $mail_html .= '							<table border="0" cellpadding="0" cellspacing="0" width="100%">';
$mail_html = $mail_html .= '								<tr>';
$mail_html = $mail_html .= '									<td width="50px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '										&nbsp;';
$mail_html = $mail_html .= '									</td>';
$mail_html = $mail_html .= '									<td width="640px" align="left">';
$mail_html = $mail_html .= '										<img src="'.$home_url.'/html/images/mail/imglogom.jpg" alt="Rewardy" width="160" height="97" style="display: block;" />';
$mail_html = $mail_html .= '									</td>';
$mail_html = $mail_html .= '									<td width="50px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '										&nbsp;';
$mail_html = $mail_html .= '									</td>';
$mail_html = $mail_html .= '								</tr>';
$mail_html = $mail_html .= '							</table>';
$mail_html = $mail_html .= '						</td>';
$mail_html = $mail_html .= '					</tr>';
$mail_html = $mail_html .= '					<tr>';
$mail_html = $mail_html .= '						<td height="2px" bgcolor="#38c9d2" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '							&nbsp;';
$mail_html = $mail_html .= '						</td>';
$mail_html = $mail_html .= '					</tr>';
$mail_html = $mail_html .= '					<tr>';
$mail_html = $mail_html .= '						<td height="50px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '							&nbsp;';
$mail_html = $mail_html .= '						</td>';
$mail_html = $mail_html .= '					</tr>';
$mail_html = $mail_html .= '					<tr>';
$mail_html = $mail_html .= '						<td>';
$mail_html = $mail_html .= '							<table border="0" cellpadding="0" cellspacing="0" width="100%">';
$mail_html = $mail_html .= '								<tr>';
$mail_html = $mail_html .= '									<td width="50px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '										&nbsp;';
$mail_html = $mail_html .= '									</td>';
$mail_html = $mail_html .= '									<td width="640px">';
$mail_html = $mail_html .= '										<table border="0" cellpadding="0" cellspacing="0" width="100%">';
$mail_html = $mail_html .= '											<tr>';
$mail_html = $mail_html .= '												<td align="left">';
$mail_html = $mail_html .= '													<img src="'.$home_url.'/html/images/mail/img21m.jpg" alt="비밀번호 재설정 안내" width="257" height="29" style="display: block;" />';
$mail_html = $mail_html .= '												</td>';
$mail_html = $mail_html .= '											</tr>';
$mail_html = $mail_html .= '											<tr>';
$mail_html = $mail_html .= '												<td height="20px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '													&nbsp;';
$mail_html = $mail_html .= '												</td>';
$mail_html = $mail_html .= '											</tr>';
$mail_html = $mail_html .= '											<tr>';
$mail_html = $mail_html .= '												<td style="text-align:left;font-size:13px;color:#4e4e4e;font-weight:normal;line-height:21px;font-family:AppleSDGothicNeo-Regular,\'Noto Sans KR\',\'돋움\',dotum,sans-serif;letter-spacing:-0.065px;">';
$mail_html = $mail_html .= '													안녕하세요. ['.$to_email.'] 고객님.<br/>';
$mail_html = $mail_html .= '													해당 아이디의 비밀번호 재설정 요청이 접수되었습니다.<br/>';
$mail_html = $mail_html .= '													<br/>';
$mail_html = $mail_html .= '													비밀번호 재설정을 원하시는 경우, 아래 [비밀번호 재설정] 버튼을 선택해주세요.<br/>';
$mail_html = $mail_html .= '													즉시 새로운 비밀번호로 재설정하시고 이용해주세요.<br/>';
$mail_html = $mail_html .= '													감사합니다.';
$mail_html = $mail_html .= '												</td>';
$mail_html = $mail_html .= '											</tr>';
$mail_html = $mail_html .= '											<tr>';
$mail_html = $mail_html .= '												<td height="70px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '													&nbsp;';
$mail_html = $mail_html .= '												</td>';
$mail_html = $mail_html .= '											</tr>';
$mail_html = $mail_html .= '											<tr>';
$mail_html = $mail_html .= '												<td align="left">';
$mail_html = $mail_html .= '													<img src="'.$home_url.'/html/images/mail/img22m.jpg" alt="회원정보" width="61" height="17" style="display: block;" />';
$mail_html = $mail_html .= '												</td>';
$mail_html = $mail_html .= '											</tr>';
$mail_html = $mail_html .= '											<tr>';
$mail_html = $mail_html .= '												<td height="17px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '													&nbsp;';
$mail_html = $mail_html .= '												</td>';
$mail_html = $mail_html .= '											</tr>';
$mail_html = $mail_html .= '											<tr>';
$mail_html = $mail_html .= '												<td style="border-top:1px solid #252525;border-top-color:#252525;border-top-width:1px;border-top-style:solid;">';
$mail_html = $mail_html .= '													<table border="0" cellpadding="0" cellspacing="0" width="100%">';
$mail_html = $mail_html .= '														<tr>';
$mail_html = $mail_html .= '															<td bgcolor="#f5f5f5" align="center" width="160px" style="text-align:center;font-size:13px;color:#252525;font-weight:bold;line-height:23px;font-family:AppleSDGothicNeo-Regular,\'Noto Sans KR\',\'돋움\',dotum,sans-serif;border-bottom:1px solid #e1e1e1;border-right:1px solid #e1e1e1;border-bottom-color:#e1e1e1;border-bottom-width:1px;border-bottom-style:solid;border-right-color:#e1e1e1;border-right-width:1px;border-right-style:solid;padding-top:15px;padding-right:0px;padding-bottom:15px;padding-left:0px;letter-spacing:-0.1px;background-color:#f5f5f5;">';
$mail_html = $mail_html .= '																<b>회원명</b>';
$mail_html = $mail_html .= '															</td>';
$mail_html = $mail_html .= '															<td bgcolor="#ffffff" align="left" width="480px" style="text-align:left;font-size:13px;color:#252525;font-weight:normal;line-height:23px;font-family:AppleSDGothicNeo-Regular,\'Noto Sans KR\',\'돋움\',dotum,sans-serif;border-bottom:1px solid #e1e1e1;border-bottom-color:#e1e1e1;border-bottom-width:1px;border-bottom-style:solid;padding-top:15px;padding-right:0px;padding-bottom:15px;padding-left:15px;letter-spacing:0.02px;background-color:#ffffff;">';
$mail_html = $mail_html .= '																'.$user_name.'';
$mail_html = $mail_html .= '															</td>';
$mail_html = $mail_html .= '														</tr>';
$mail_html = $mail_html .= '														<tr>';
$mail_html = $mail_html .= '															<td bgcolor="#f5f5f5" align="center" width="160px" style="text-align:center;font-size:13px;color:#252525;font-weight:bold;line-height:23px;font-family:AppleSDGothicNeo-Regular,\'Noto Sans KR\',\'돋움\',dotum,sans-serif;border-bottom:1px solid #e1e1e1;border-right:1px solid #e1e1e1;border-bottom-color:#e1e1e1;border-bottom-width:1px;border-bottom-style:solid;border-right-color:#e1e1e1;border-right-width:1px;border-right-style:solid;padding-top:15px;padding-right:0px;padding-bottom:15px;padding-left:0px;letter-spacing:-0.1px;background-color:#f5f5f5;">';
$mail_html = $mail_html .= '																<b>아이디</b>';
$mail_html = $mail_html .= '															</td>';
$mail_html = $mail_html .= '															<td bgcolor="#ffffff" align="left" width="480px" style="text-align:left;font-size:13px;color:#252525;font-weight:normal;line-height:23px;font-family:AppleSDGothicNeo-Regular,\'Noto Sans KR\',\'돋움\',dotum,sans-serif;border-bottom:1px solid #e1e1e1;border-bottom-color:#e1e1e1;border-bottom-width:1px;border-bottom-style:solid;padding-top:15px;padding-right:0px;padding-bottom:15px;padding-left:15px;letter-spacing:0.02px;background-color:#ffffff;">';
$mail_html = $mail_html .= '																'.$to_email.'';
$mail_html = $mail_html .= '															</td>';
$mail_html = $mail_html .= '														</tr>';
$mail_html = $mail_html .= '														<tr>';
$mail_html = $mail_html .= '															<td bgcolor="#f5f5f5" align="center" width="160px" style="text-align:center;font-size:13px;color:#252525;font-weight:bold;line-height:23px;font-family:AppleSDGothicNeo-Regular,\'Noto Sans KR\',\'돋움\',dotum,sans-serif;border-bottom:1px solid #e1e1e1;border-right:1px solid #e1e1e1;border-bottom-color:#e1e1e1;border-bottom-width:1px;border-bottom-style:solid;border-right-color:#e1e1e1;border-right-width:1px;border-right-style:solid;padding-top:15px;padding-right:0px;padding-bottom:15px;padding-left:0px;letter-spacing:-0.1px;background-color:#f5f5f5;">';
$mail_html = $mail_html .= '																<b>업체명</b>';
$mail_html = $mail_html .= '															</td>';
$mail_html = $mail_html .= '															<td bgcolor="#ffffff" align="left" width="480px" style="text-align:left;font-size:13px;color:#252525;font-weight:normal;line-height:23px;font-family:AppleSDGothicNeo-Regular,\'Noto Sans KR\',\'돋움\',dotum,sans-serif;border-bottom:1px solid #e1e1e1;border-bottom-color:#e1e1e1;border-bottom-width:1px;border-bottom-style:solid;padding-top:15px;padding-right:0px;padding-bottom:15px;padding-left:15px;letter-spacing:0.02px;background-color:#ffffff;">';
$mail_html = $mail_html .= '																'.$to_company_name.'';
$mail_html = $mail_html .= '															</td>';
$mail_html = $mail_html .= '														</tr>';
$mail_html = $mail_html .= '													</table>';
$mail_html = $mail_html .= '												</td>';
$mail_html = $mail_html .= '											</tr>';
$mail_html = $mail_html .= '										</table>';
$mail_html = $mail_html .= '									</td>';
$mail_html = $mail_html .= '									<td width="50px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '										&nbsp;';
$mail_html = $mail_html .= '									</td>';
$mail_html = $mail_html .= '								</tr>';
$mail_html = $mail_html .= '							</table>';
$mail_html = $mail_html .= '						</td>';
$mail_html = $mail_html .= '					</tr>';
$mail_html = $mail_html .= '					<tr>';
$mail_html = $mail_html .= '						<td height="50px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '							&nbsp;';
$mail_html = $mail_html .= '						</td>';
$mail_html = $mail_html .= '					</tr>';
$mail_html = $mail_html .= '					<tr>';
$mail_html = $mail_html .= '						<td>';
$mail_html = $mail_html .= '							<table border="0" cellpadding="0" cellspacing="0" width="100%">';
$mail_html = $mail_html .= '								<tr>';
$mail_html = $mail_html .= '									<td>';
$mail_html = $mail_html .= '										<table border="0" cellpadding="0" cellspacing="0" width="100%">';
$mail_html = $mail_html .= '											<tr>';
$mail_html = $mail_html .= '												<td width="253px" height="50px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '													&nbsp;';
$mail_html = $mail_html .= '												</td>';
$mail_html = $mail_html .= '												<td bgcolor="#38c9d2" width="234px" height="50px" align="center">';
$mail_html = $mail_html .= '													<a href="'.$reset_url.'" target="_blank" style="font-size:13px;color:#ffffff;text-align:center;line-height:50px;text-decoration:underline;display:block;padding:0;margin:0;"><img src="'.$home_url.'/html/images/mail/img23m.jpg" alt="비밀번호 재설정" width="234" height="50" style="display: block;" /></a>';
$mail_html = $mail_html .= '												</td>';
$mail_html = $mail_html .= '												<td width="253px" height="50px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '													&nbsp;';
$mail_html = $mail_html .= '												</td>';
$mail_html = $mail_html .= '											</tr>';
$mail_html = $mail_html .= '										</table>';
$mail_html = $mail_html .= '									</td>';
$mail_html = $mail_html .= '								</tr>';
$mail_html = $mail_html .= '							</table>';
$mail_html = $mail_html .= '						</td>';
$mail_html = $mail_html .= '					</tr>';
$mail_html = $mail_html .= '					<tr>';
$mail_html = $mail_html .= '						<td height="90px" style="font-size:0;line-height:0;">';
$mail_html = $mail_html .= '							&nbsp;';
$mail_html = $mail_html .= '						</td>';
$mail_html = $mail_html .= '					</tr>';
$mail_html = $mail_html .= '					<tr>';
$mail_html = $mail_html .= '						<td>';
$mail_html = $mail_html .= '							<table border="0" cellpadding="0" cellspacing="0" width="100%">';
$mail_html = $mail_html .= '								<tr>';
$mail_html = $mail_html .= '									<td align="left" style="text-align:left;font-size:12px;color:#7c7c7c;line-height:18px;font-family:AppleSDGothicNeo-Regular,\'Noto Sans KR\',\'돋움\',dotum,sans-serif;padding-top:35px;padding-right:50px;padding-bottom:35px;padding-left:50px;letter-spacing:0px;" bgcolor="#f1f1f1">';
$mail_html = $mail_html .= '										본 메일은 발신 전용으로 회신 되지 않습니다.<br/>';
$mail_html = $mail_html .= '										문의 사항은 리워디 <a style="text-align:left;font-size:12px;color:#252525;line-height:18px;font-family:AppleSDGothicNeo-Regular,\'Noto Sans KR\',\'돋움\',dotum,sans-serif;text-decoration:underline;" target="_blank" href="#"><font color="#252525">고객센터 1:1 문의</font></a> 또는 1588-8443을 이용해주세요.<br/>';
$mail_html = $mail_html .= '										<br/>';
$mail_html = $mail_html .= '										㈜ 비즈폼  | 부산광역시 해운대구 해운대해변로 257, 1601호 (하버타운) | 대표 : 이선규<br/>';
$mail_html = $mail_html .= '										Tel : 1588-8443 | Fax : 080-082-4990 | <a style="text-align:left;font-size:12px;color:#252525;line-height:18px;font-family:AppleSDGothicNeo-Regular,\'Noto Sans KR\',\'돋움\',dotum,sans-serif;text-decoration:underline;" target="_blank" href="mailto:support@bizforms.co.kr"><font color="#252525">support@bizforms.co.kr</font></a>';
$mail_html = $mail_html .= '									</td>';
$mail_html = $mail_html .= '								</tr>';
$mail_html = $mail_html .= '							</table>';
$mail_html = $mail_html .= '						</td>';
$mail_html = $mail_html .= '					</tr>';
$mail_html = $mail_html .= '				</table>';
$mail_html = $mail_html .= '			</td>';
$mail_html = $mail_html .= '		</tr>';
$mail_html = $mail_html .= '	</table>';
$mail_html = $mail_html .= '</body>';
$mail_html = $mail_html .= '</html>';
?>