-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgc0nrtCjNXoKs/Pt0
OaL1seQ3UgmvAcBsawxPZWfohNCgCgYIKoZIzj0DAQehRANCAAQWuStq5GoNFdo9
VV/IbX/spqjCIdxrNcuOzAGq4Iou1sdkbVLT5m8VRyRMs0eaCyE7HgTC4SllL/8a
RIIxeRxm
-----END PRIVATE KEY-----